/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model

import org.openapi.google.model.LatLngLiteral

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * A rectangle in geographical coordinates from points at the southwest and northeast corners.
 *
 * @param northeast 
 * @param southwest 
 */

data class Bounds (

    @field:JsonProperty("northeast")
    val northeast: LatLngLiteral,

    @field:JsonProperty("southwest")
    val southwest: LatLngLiteral

)

