/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Attributes used to describe a cell tower. The following optional fields are not currently used, but may be included if values are available: `age`, `signalStrength`, `timingAdvance`.
 *
 * @param cellId Unique identifier of the cell. On GSM, this is the Cell ID (CID); CDMA networks use the Base Station ID (BID). WCDMA networks use the UTRAN/GERAN Cell Identity (UC-Id), which is a 32-bit value concatenating the Radio Network Controller (RNC) and Cell ID. Specifying only the 16-bit Cell ID value in WCDMA networks may return inaccurate results.
 * @param locationAreaCode The Location Area Code (LAC) for GSM and WCDMA networks. The Network ID (NID) for CDMA networks.
 * @param mobileCountryCode The cell tower's Mobile Country Code (MCC).
 * @param mobileNetworkCode The cell tower's Mobile Network Code. This is the MNC for GSM and WCDMA; CDMA uses the System ID (SID).
 * @param age The number of milliseconds since this cell was primary. If age is 0, the cellId represents a current measurement.
 * @param signalStrength Radio signal strength measured in dBm.
 * @param timingAdvance The timing advance value.
 */

data class CellTower (

    /* Unique identifier of the cell. On GSM, this is the Cell ID (CID); CDMA networks use the Base Station ID (BID). WCDMA networks use the UTRAN/GERAN Cell Identity (UC-Id), which is a 32-bit value concatenating the Radio Network Controller (RNC) and Cell ID. Specifying only the 16-bit Cell ID value in WCDMA networks may return inaccurate results. */
    @field:JsonProperty("cellId")
    val cellId: kotlin.Int,

    /* The Location Area Code (LAC) for GSM and WCDMA networks. The Network ID (NID) for CDMA networks. */
    @field:JsonProperty("locationAreaCode")
    val locationAreaCode: kotlin.Int,

    /* The cell tower's Mobile Country Code (MCC). */
    @field:JsonProperty("mobileCountryCode")
    val mobileCountryCode: kotlin.Int,

    /* The cell tower's Mobile Network Code. This is the MNC for GSM and WCDMA; CDMA uses the System ID (SID). */
    @field:JsonProperty("mobileNetworkCode")
    val mobileNetworkCode: kotlin.Int,

    /* The number of milliseconds since this cell was primary. If age is 0, the cellId represents a current measurement. */
    @field:JsonProperty("age")
    val age: kotlin.Int? = null,

    /* Radio signal strength measured in dBm. */
    @field:JsonProperty("signalStrength")
    val signalStrength: java.math.BigDecimal? = null,

    /* The timing advance value. */
    @field:JsonProperty("timingAdvance")
    val timingAdvance: java.math.BigDecimal? = null

)

