/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model

import org.openapi.google.model.LatLngLiteral

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param location 
 * @param name The name of the transit stop.
 */

data class DirectionsTransitStop (

    @field:JsonProperty("location")
    val location: LatLngLiteral,

    /* The name of the transit stop. */
    @field:JsonProperty("name")
    val name: kotlin.String

)

