/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param name The name of this transit agency.
 * @param phone The transit agency's phone number.
 * @param url The transit agency's URL.
 */

data class DirectionsTransitAgency (

    /* The name of this transit agency. */
    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    /* The transit agency's phone number. */
    @field:JsonProperty("phone")
    val phone: kotlin.String? = null,

    /* The transit agency's URL. */
    @field:JsonProperty("url")
    val url: kotlin.String? = null

)

