/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model

import org.openapi.google.model.DirectionsGeocodedWaypoint
import org.openapi.google.model.DirectionsRoute
import org.openapi.google.model.DirectionsStatus
import org.openapi.google.model.TravelMode

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param routes Contains an array of routes from the origin to the destination. Routes consist of nested Legs and Steps.
 * @param status 
 * @param geocodedWaypoints Contains an array with details about the geocoding of origin, destination and waypoints. Elements in the geocoded_waypoints array correspond, by their zero-based position, to the origin, the waypoints in the order they are specified, and the destination.  These details will not be present for waypoints specified as textual latitude/longitude values if the service returns no results. This is because such waypoints are only reverse geocoded to obtain their representative address after a route has been found. An empty JSON object will occupy the corresponding places in the geocoded_waypoints array. 
 * @param availableTravelModes Contains an array of available travel modes. This field is returned when a request specifies a travel mode and gets no results. The array contains the available travel modes in the countries of the given set of waypoints. This field is not returned if one or more of the waypoints are 'via waypoints'.
 * @param errorMessage When the service returns a status code other than `OK`, there may be an additional `error_message` field within the response object. This field contains more detailed information about the reasons behind the given status code. This field is not always returned, and its content is subject to change. 
 */

data class DirectionsResponse (

    /* Contains an array of routes from the origin to the destination. Routes consist of nested Legs and Steps. */
    @field:JsonProperty("routes")
    val routes: kotlin.collections.List<DirectionsRoute>,

    @field:JsonProperty("status")
    val status: DirectionsStatus,

    /* Contains an array with details about the geocoding of origin, destination and waypoints. Elements in the geocoded_waypoints array correspond, by their zero-based position, to the origin, the waypoints in the order they are specified, and the destination.  These details will not be present for waypoints specified as textual latitude/longitude values if the service returns no results. This is because such waypoints are only reverse geocoded to obtain their representative address after a route has been found. An empty JSON object will occupy the corresponding places in the geocoded_waypoints array.  */
    @field:JsonProperty("geocoded_waypoints")
    val geocodedWaypoints: kotlin.collections.List<DirectionsGeocodedWaypoint>? = null,

    /* Contains an array of available travel modes. This field is returned when a request specifies a travel mode and gets no results. The array contains the available travel modes in the countries of the given set of waypoints. This field is not returned if one or more of the waypoints are 'via waypoints'. */
    @field:JsonProperty("available_travel_modes")
    val availableTravelModes: kotlin.collections.List<TravelMode>? = null,

    /* When the service returns a status code other than `OK`, there may be an additional `error_message` field within the response object. This field contains more detailed information about the reasons behind the given status code. This field is not always returned, and its content is subject to change.  */
    @field:JsonProperty("error_message")
    val errorMessage: kotlin.String? = null

)

