/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model

import org.openapi.google.model.DirectionsTransitLine
import org.openapi.google.model.DirectionsTransitStop
import org.openapi.google.model.TimeZoneTextValueObject

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Additional information that is not relevant for other modes of transportation.
 *
 * @param arrivalStop 
 * @param arrivalTime 
 * @param departureStop 
 * @param departureTime 
 * @param headsign Specifies the direction in which to travel on this line, as it is marked on the vehicle or at the departure stop. This will often be the terminus station.
 * @param headway Specifies the expected number of seconds between departures from the same stop at this time. For example, with a `headway` value of 600, you would expect a ten minute wait if you should miss your bus.
 * @param line 
 * @param numStops The number of stops from the departure to the arrival stop. This includes the arrival stop, but not the departure stop. For example, if your directions involve leaving from Stop A, passing through stops B and C, and arriving at stop D, `num_stops` will return 3.
 * @param tripShortName The text that appears in schedules and sign boards to identify a transit trip to passengers. The text should uniquely identify a trip within a service day. For example, \"538\" is the `trip_short_name` of the Amtrak train that leaves San Jose, CA at 15:10 on weekdays to Sacramento, CA.
 */

data class DirectionsTransitDetails (

    @field:JsonProperty("arrival_stop")
    val arrivalStop: DirectionsTransitStop? = null,

    @field:JsonProperty("arrival_time")
    val arrivalTime: TimeZoneTextValueObject? = null,

    @field:JsonProperty("departure_stop")
    val departureStop: DirectionsTransitStop? = null,

    @field:JsonProperty("departure_time")
    val departureTime: TimeZoneTextValueObject? = null,

    /* Specifies the direction in which to travel on this line, as it is marked on the vehicle or at the departure stop. This will often be the terminus station. */
    @field:JsonProperty("headsign")
    val headsign: kotlin.String? = null,

    /* Specifies the expected number of seconds between departures from the same stop at this time. For example, with a `headway` value of 600, you would expect a ten minute wait if you should miss your bus. */
    @field:JsonProperty("headway")
    val headway: kotlin.Int? = null,

    @field:JsonProperty("line")
    val line: DirectionsTransitLine? = null,

    /* The number of stops from the departure to the arrival stop. This includes the arrival stop, but not the departure stop. For example, if your directions involve leaving from Stop A, passing through stops B and C, and arriving at stop D, `num_stops` will return 3. */
    @field:JsonProperty("num_stops")
    val numStops: kotlin.Int? = null,

    /* The text that appears in schedules and sign boards to identify a transit trip to passengers. The text should uniquely identify a trip within a service day. For example, \"538\" is the `trip_short_name` of the Amtrak train that leaves San Jose, CA at 15:10 on weekdays to Sacramento, CA. */
    @field:JsonProperty("trip_short_name")
    val tripShortName: kotlin.String? = null

)

