/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model

import org.openapi.google.model.DirectionsStep
import org.openapi.google.model.DirectionsTrafficSpeedEntry
import org.openapi.google.model.DirectionsViaWaypoint
import org.openapi.google.model.LatLngLiteral
import org.openapi.google.model.TextValueObject
import org.openapi.google.model.TimeZoneTextValueObject

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param endAddress Contains the human-readable address (typically a street address) from reverse geocoding the `end_location` of this leg. This content is meant to be read as-is. Do not programmatically parse the formatted address.
 * @param endLocation 
 * @param startAddress Contains the human-readable address (typically a street address) resulting from reverse geocoding the `start_location` of this leg. This content is meant to be read as-is. Do not programmatically parse the formatted address.
 * @param startLocation 
 * @param steps An array of steps denoting information about each separate step of the leg of the journey.
 * @param trafficSpeedEntry Information about traffic speed along the leg.
 * @param viaWaypoint The locations of via waypoints along this leg.
 * @param arrivalTime 
 * @param departureTime 
 * @param distance 
 * @param duration 
 * @param durationInTraffic 
 */

data class DirectionsLeg (

    /* Contains the human-readable address (typically a street address) from reverse geocoding the `end_location` of this leg. This content is meant to be read as-is. Do not programmatically parse the formatted address. */
    @field:JsonProperty("end_address")
    val endAddress: kotlin.String,

    @field:JsonProperty("end_location")
    val endLocation: LatLngLiteral,

    /* Contains the human-readable address (typically a street address) resulting from reverse geocoding the `start_location` of this leg. This content is meant to be read as-is. Do not programmatically parse the formatted address. */
    @field:JsonProperty("start_address")
    val startAddress: kotlin.String,

    @field:JsonProperty("start_location")
    val startLocation: LatLngLiteral,

    /* An array of steps denoting information about each separate step of the leg of the journey. */
    @field:JsonProperty("steps")
    val steps: kotlin.collections.List<DirectionsStep>,

    /* Information about traffic speed along the leg. */
    @field:JsonProperty("traffic_speed_entry")
    @Deprecated(message = "This property is deprecated.")
    val trafficSpeedEntry: kotlin.collections.List<DirectionsTrafficSpeedEntry>,

    /* The locations of via waypoints along this leg. */
    @field:JsonProperty("via_waypoint")
    val viaWaypoint: kotlin.collections.List<DirectionsViaWaypoint>,

    @field:JsonProperty("arrival_time")
    val arrivalTime: TimeZoneTextValueObject? = null,

    @field:JsonProperty("departure_time")
    val departureTime: TimeZoneTextValueObject? = null,

    @field:JsonProperty("distance")
    val distance: TextValueObject? = null,

    @field:JsonProperty("duration")
    val duration: TextValueObject? = null,

    @field:JsonProperty("duration_in_traffic")
    val durationInTraffic: TextValueObject? = null

)

