/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param speedCategory The current traffic/speed conditions on this portion of a path.
 * @param offsetMeters The offset along the path (in meters) up to which this speed category is valid.
 */

@Deprecated(message = "This schema is deprecated.")
data class DirectionsTrafficSpeedEntry (

    /* The current traffic/speed conditions on this portion of a path. */
    @field:JsonProperty("speed_category")
    val speedCategory: kotlin.String,

    /* The offset along the path (in meters) up to which this speed category is valid. */
    @field:JsonProperty("offset_meters")
    val offsetMeters: java.math.BigDecimal

)

