/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The status field within the Directions response object contains the status of the request, and may contain debugging information to help you track down why the Directions service failed. The status field may contain the following values:  - `OK` indicates the response contains a valid result. - `NOT_FOUND` indicates at least one of the locations specified in the request's origin, destination, or waypoints could not be geocoded. - `ZERO_RESULTS` indicates no route could be found between the origin and destination. - `MAX_WAYPOINTS_EXCEEDED` indicates that too many waypoints were provided in the request. For applications using the Directions API as a web service, or the directions service in the Maps JavaScript API, the maximum allowed number of waypoints is 25, plus the origin and destination. - `MAX_ROUTE_LENGTH_EXCEEDED` indicates the requested route is too long and cannot be processed. This error occurs when more complex directions are returned. Try reducing the number of waypoints, turns, or instructions. - `INVALID_REQUEST` indicates that the provided request was invalid. Common causes of this status include an invalid parameter or parameter value. - `OVER_DAILY_LIMIT` indicates any of the following:     - The API key is missing or invalid.     - Billing has not been enabled on your account.     - A self-imposed usage cap has been exceeded.     - The provided method of payment is no longer valid (for example, a credit card has expired).     See the [Maps FAQ](https://developers.google.com/maps/faq#over-limit-key-error) to learn how to fix this. - `OVER_QUERY_LIMIT` indicates the service has received too many requests from your application within the allowed time period. - `REQUEST_DENIED` indicates that the service denied use of the directions service by your application. - `UNKNOWN_ERROR` indicates a directions request could not be processed due to a server error. The request may succeed if you try again. 
 *
 * Values: OK,NOT_FOUND,ZERO_RESULTS,MAX_WAYPOINTS_EXCEEDED,MAX_ROUTE_LENGTH_EXCEEDED,INVALID_REQUEST,OVER_DAILY_LIMIT,OVER_QUERY_LIMIT,REQUEST_DENIED,UNKNOWN_ERROR
 */

enum class DirectionsStatus(val value: kotlin.String) {

    @JsonProperty(value = "OK")
    OK("OK"),

    @JsonProperty(value = "NOT_FOUND")
    NOT_FOUND("NOT_FOUND"),

    @JsonProperty(value = "ZERO_RESULTS")
    ZERO_RESULTS("ZERO_RESULTS"),

    @JsonProperty(value = "MAX_WAYPOINTS_EXCEEDED")
    MAX_WAYPOINTS_EXCEEDED("MAX_WAYPOINTS_EXCEEDED"),

    @JsonProperty(value = "MAX_ROUTE_LENGTH_EXCEEDED")
    MAX_ROUTE_LENGTH_EXCEEDED("MAX_ROUTE_LENGTH_EXCEEDED"),

    @JsonProperty(value = "INVALID_REQUEST")
    INVALID_REQUEST("INVALID_REQUEST"),

    @JsonProperty(value = "OVER_DAILY_LIMIT")
    OVER_DAILY_LIMIT("OVER_DAILY_LIMIT"),

    @JsonProperty(value = "OVER_QUERY_LIMIT")
    OVER_QUERY_LIMIT("OVER_QUERY_LIMIT"),

    @JsonProperty(value = "REQUEST_DENIED")
    REQUEST_DENIED("REQUEST_DENIED"),

    @JsonProperty(value = "UNKNOWN_ERROR")
    UNKNOWN_ERROR("UNKNOWN_ERROR");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is DirectionsStatus) "$data" else null

        /**
         * Returns a valid [DirectionsStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): DirectionsStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

