/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Status codes returned by service. - `OK` indicates the response contains a valid result. - `INVALID_REQUEST` indicates that the provided request was invalid. - `MAX_ELEMENTS_EXCEEDED` indicates that the product of origins and destinations exceeds the per-query limit. - `MAX_DIMENSIONS_EXCEEDED` indicates that the number of origins or destinations exceeds the per-query limit. - `OVER_DAILY_LIMIT` indicates any of the following:   - The API key is missing or invalid.   - Billing has not been enabled on your account.   - A self-imposed usage cap has been exceeded.   - The provided method of payment is no longer valid (for example, a credit card has expired). - `OVER_QUERY_LIMIT` indicates the service has received too many requests from your application within the allowed time period. - `REQUEST_DENIED` indicates that the service denied use of the Distance Matrix service by your application. - `UNKNOWN_ERROR` indicates a Distance Matrix request could not be processed due to a server error. The request may succeed if you try again. 
 *
 * Values: OK,INVALID_REQUEST,MAX_ELEMENTS_EXCEEDED,MAX_DIMENSIONS_EXCEEDED,OVER_DAILY_LIMIT,OVER_QUERY_LIMIT,REQUEST_DENIED,UNKNOWN_ERROR
 */

enum class DistanceMatrixStatus(val value: kotlin.String) {

    @JsonProperty(value = "OK")
    OK("OK"),

    @JsonProperty(value = "INVALID_REQUEST")
    INVALID_REQUEST("INVALID_REQUEST"),

    @JsonProperty(value = "MAX_ELEMENTS_EXCEEDED")
    MAX_ELEMENTS_EXCEEDED("MAX_ELEMENTS_EXCEEDED"),

    @JsonProperty(value = "MAX_DIMENSIONS_EXCEEDED")
    MAX_DIMENSIONS_EXCEEDED("MAX_DIMENSIONS_EXCEEDED"),

    @JsonProperty(value = "OVER_DAILY_LIMIT")
    OVER_DAILY_LIMIT("OVER_DAILY_LIMIT"),

    @JsonProperty(value = "OVER_QUERY_LIMIT")
    OVER_QUERY_LIMIT("OVER_QUERY_LIMIT"),

    @JsonProperty(value = "REQUEST_DENIED")
    REQUEST_DENIED("REQUEST_DENIED"),

    @JsonProperty(value = "UNKNOWN_ERROR")
    UNKNOWN_ERROR("UNKNOWN_ERROR");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is DistanceMatrixStatus) "$data" else null

        /**
         * Returns a valid [DistanceMatrixStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): DistanceMatrixStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

