/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * - `OK` indicates the response contains a valid result. - `NOT_FOUND` indicates that the origin and/or destination of this pairing could not be geocoded. - `ZERO_RESULTS` indicates no route could be found between the origin and destination. - `MAX_ROUTE_LENGTH_EXCEEDED` indicates the requested route is too long and cannot be processed. 
 *
 * Values: OK,NOT_FOUND,ZERO_RESULTS,MAX_ROUTE_LENGTH_EXCEEDED
 */

enum class DistanceMatrixElementStatus(val value: kotlin.String) {

    @JsonProperty(value = "OK")
    OK("OK"),

    @JsonProperty(value = "NOT_FOUND")
    NOT_FOUND("NOT_FOUND"),

    @JsonProperty(value = "ZERO_RESULTS")
    ZERO_RESULTS("ZERO_RESULTS"),

    @JsonProperty(value = "MAX_ROUTE_LENGTH_EXCEEDED")
    MAX_ROUTE_LENGTH_EXCEEDED("MAX_ROUTE_LENGTH_EXCEEDED");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is DistanceMatrixElementStatus) "$data" else null

        /**
         * Returns a valid [DistanceMatrixElementStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): DistanceMatrixElementStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

