/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model

import org.openapi.google.model.DistanceMatrixRow
import org.openapi.google.model.DistanceMatrixStatus

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param originAddresses An array of addresses as returned by the API from your original request. These are formatted by the geocoder and localized according to the language parameter passed with the request. This content is meant to be read as-is. Do not programatically parse the formatted addresses.
 * @param destinationAddresses An array of addresses as returned by the API from your original request. As with `origin_addresses`, these are localized if appropriate. This content is meant to be read as-is. Do not programatically parse the formatted addresses.
 * @param rows An array of elements, which in turn each contain a `status`, `duration`, and `distance` element.
 * @param status 
 * @param errorMessage A string containing the human-readable text of any errors encountered while the request was being processed.
 */

data class DistanceMatrixResponse (

    /* An array of addresses as returned by the API from your original request. These are formatted by the geocoder and localized according to the language parameter passed with the request. This content is meant to be read as-is. Do not programatically parse the formatted addresses. */
    @field:JsonProperty("origin_addresses")
    val originAddresses: kotlin.collections.List<kotlin.String>,

    /* An array of addresses as returned by the API from your original request. As with `origin_addresses`, these are localized if appropriate. This content is meant to be read as-is. Do not programatically parse the formatted addresses. */
    @field:JsonProperty("destination_addresses")
    val destinationAddresses: kotlin.collections.List<kotlin.String>,

    /* An array of elements, which in turn each contain a `status`, `duration`, and `distance` element. */
    @field:JsonProperty("rows")
    val rows: kotlin.collections.List<DistanceMatrixRow>,

    @field:JsonProperty("status")
    val status: DistanceMatrixStatus,

    /* A string containing the human-readable text of any errors encountered while the request was being processed. */
    @field:JsonProperty("error_message")
    val errorMessage: kotlin.String? = null

)

