/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model

import org.openapi.google.model.DistanceMatrixElementStatus
import org.openapi.google.model.Fare
import org.openapi.google.model.TextValueObject

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param status 
 * @param fare 
 * @param distance 
 * @param durationInTraffic 
 * @param duration 
 */

data class DistanceMatrixElement (

    @field:JsonProperty("status")
    val status: DistanceMatrixElementStatus,

    @field:JsonProperty("fare")
    val fare: Fare? = null,

    @field:JsonProperty("distance")
    val distance: TextValueObject? = null,

    @field:JsonProperty("duration_in_traffic")
    val durationInTraffic: TextValueObject? = null,

    @field:JsonProperty("duration")
    val duration: TextValueObject? = null

)

