/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Status codes returned by service. - `OK` indicating the API request was successful. - `DATA_NOT_AVAILABLE` indicating that there's no available data for the input locations.  - `INVALID_REQUEST` indicating the API request was malformed. - `OVER_DAILY_LIMIT` indicating any of the following:   - The API key is missing or invalid.   - Billing has not been enabled on your account.   - A self-imposed usage cap has been exceeded.   - The provided method of payment is no longer valid (for example, a credit card has expired). - `OVER_QUERY_LIMIT` indicating the requestor has exceeded quota. - `REQUEST_DENIED` indicating the API did not complete the request. - `UNKNOWN_ERROR` indicating an unknown error. 
 *
 * Values: OK,DATA_NOT_AVAILABLE,INVALID_REQUEST,OVER_DAILY_LIMIT,OVER_QUERY_LIMIT,REQUEST_DENIED,UNKNOWN_ERROR
 */

enum class ElevationStatus(val value: kotlin.String) {

    @JsonProperty(value = "OK")
    OK("OK"),

    @JsonProperty(value = "DATA_NOT_AVAILABLE")
    DATA_NOT_AVAILABLE("DATA_NOT_AVAILABLE"),

    @JsonProperty(value = "INVALID_REQUEST")
    INVALID_REQUEST("INVALID_REQUEST"),

    @JsonProperty(value = "OVER_DAILY_LIMIT")
    OVER_DAILY_LIMIT("OVER_DAILY_LIMIT"),

    @JsonProperty(value = "OVER_QUERY_LIMIT")
    OVER_QUERY_LIMIT("OVER_QUERY_LIMIT"),

    @JsonProperty(value = "REQUEST_DENIED")
    REQUEST_DENIED("REQUEST_DENIED"),

    @JsonProperty(value = "UNKNOWN_ERROR")
    UNKNOWN_ERROR("UNKNOWN_ERROR");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ElevationStatus) "$data" else null

        /**
         * Returns a valid [ElevationStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ElevationStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

