/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model

import org.openapi.google.model.LatLngLiteral

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param elevation 
 * @param resolution 
 * @param location 
 */

data class Elevation200ResponseResultsInner (

    @field:JsonProperty("elevation")
    val elevation: java.math.BigDecimal? = null,

    @field:JsonProperty("resolution")
    val resolution: java.math.BigDecimal? = null,

    @field:JsonProperty("location")
    val location: LatLngLiteral? = null

)

