/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model

import org.openapi.google.model.LatLngLiteral

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param elevation The elevation of the location in meters.
 * @param location 
 * @param resolution The value indicating the maximum distance between data points from which the elevation was interpolated, in meters. This property will be missing if the resolution is not known. Note that elevation data becomes more coarse (larger resolution values) when multiple points are passed. To obtain the most accurate elevation value for a point, it should be queried independently.
 */

data class ElevationResult (

    /* The elevation of the location in meters. */
    @field:JsonProperty("elevation")
    val elevation: java.math.BigDecimal,

    @field:JsonProperty("location")
    val location: LatLngLiteral,

    /* The value indicating the maximum distance between data points from which the elevation was interpolated, in meters. This property will be missing if the resolution is not known. Note that elevation data becomes more coarse (larger resolution values) when multiple points are passed. To obtain the most accurate elevation value for a point, it should be queried independently. */
    @field:JsonProperty("resolution")
    val resolution: java.math.BigDecimal? = null

)

