/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model

import org.openapi.google.model.ElevationResult
import org.openapi.google.model.ElevationStatus

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param status 
 * @param results 
 * @param errorMessage When the service returns a status code other than `OK`, there may be an additional `error_message` field within the response object. This field contains more detailed information about thereasons behind the given status code. This field is not always returned, and its content is subject to change. 
 */

data class ElevationResponse (

    @field:JsonProperty("status")
    val status: ElevationStatus,

    @field:JsonProperty("results")
    val results: kotlin.collections.List<ElevationResult>,

    /* When the service returns a status code other than `OK`, there may be an additional `error_message` field within the response object. This field contains more detailed information about thereasons behind the given status code. This field is not always returned, and its content is subject to change.  */
    @field:JsonProperty("error_message")
    val errorMessage: kotlin.String? = null

)

