/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model

import org.openapi.google.model.FieldViolation

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param atType The type of error.
 * @param message A short description of the error.
 * @param reason A reason for the error.
 * @param domain The domain in which the error occurred.
 * @param metadata Additional metadata about the error.
 * @param fieldViolations A list of field violations.
 */

data class ErrorDetail (

    /* The type of error. */
    @field:JsonProperty("@type")
    val atType: kotlin.String? = null,

    /* A short description of the error. */
    @field:JsonProperty("message")
    val message: kotlin.String? = null,

    /* A reason for the error. */
    @field:JsonProperty("reason")
    val reason: kotlin.String? = null,

    /* The domain in which the error occurred. */
    @field:JsonProperty("domain")
    val domain: kotlin.String? = null,

    /* Additional metadata about the error. */
    @field:JsonProperty("metadata")
    val metadata: kotlin.Any? = null,

    /* A list of field violations. */
    @field:JsonProperty("fieldViolations")
    val fieldViolations: kotlin.collections.List<FieldViolation>? = null

)

