/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The total fare for the route.  ``` {   \"currency\" : \"USD\",   \"value\" : 6,   \"text\" : \"$6.00\" } ``` 
 *
 * @param currency An [ISO 4217 currency code](https://en.wikipedia.org/wiki/ISO_4217) indicating the currency that the amount is expressed in.
 * @param `value` The total fare amount, in the currency specified.
 * @param text The total fare amount, formatted in the requested language.
 */

data class Fare (

    /* An [ISO 4217 currency code](https://en.wikipedia.org/wiki/ISO_4217) indicating the currency that the amount is expressed in. */
    @field:JsonProperty("currency")
    val currency: kotlin.String,

    /* The total fare amount, in the currency specified. */
    @field:JsonProperty("value")
    val `value`: java.math.BigDecimal,

    /* The total fare amount, formatted in the requested language. */
    @field:JsonProperty("text")
    val text: kotlin.String

)

