/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param `field` The name of the invalid field.
 * @param description A short description of the error.
 */

data class FieldViolation (

    /* The name of the invalid field. */
    @field:JsonProperty("field")
    val `field`: kotlin.String,

    /* A short description of the error. */
    @field:JsonProperty("description")
    val description: kotlin.String

)

