/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model

import org.openapi.google.model.GeocodingResult
import org.openapi.google.model.GeocodingStatus
import org.openapi.google.model.PlusCode

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param results 
 * @param status 
 * @param plusCode 
 * @param errorMessage A short description of the error.
 */

data class GeocodingResponse (

    @field:JsonProperty("results")
    val results: kotlin.collections.List<GeocodingResult>,

    @field:JsonProperty("status")
    val status: GeocodingStatus,

    @field:JsonProperty("plus_code")
    val plusCode: PlusCode? = null,

    /* A short description of the error. */
    @field:JsonProperty("error_message")
    val errorMessage: kotlin.String? = null

)

