/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model

import org.openapi.google.model.AddressComponent
import org.openapi.google.model.GeocodingGeometry
import org.openapi.google.model.PlusCode

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param addressComponents An array containing the separate components applicable to this address.
 * @param formattedAddress The human-readable address of this location.
 * @param geometry 
 * @param placeId A unique identifier that can be used with other Google APIs. For example, you can use the `place_id` in a Places API request to get details of a local business, such as phone number, opening hours, user reviews, and more. See the [place ID overview](https://developers.google.com/places/place-id).
 * @param types The `types[]` array indicates the type of the returned result. This array contains a set of zero or more tags identifying the type of feature returned in the result. For example, a geocode of \"Chicago\" returns \"locality\" which indicates that \"Chicago\" is a city, and also returns \"political\" which indicates it is a political entity.
 * @param plusCode 
 * @param postcodeLocalities An array denoting all the localities contained in a postal code. This is only present when the result is a postal code that contains multiple localities.
 * @param partialMatch Indicates that the geocoder did not return an exact match for the original request, though it was able to match part of the requested address. You may wish to examine the original request for misspellings and/or an incomplete address.  Partial matches most often occur for street addresses that do not exist within the locality you pass in the request. Partial matches may also be returned when a request matches two or more locations in the same locality. 
 */

data class GeocodingResult (

    /* An array containing the separate components applicable to this address. */
    @field:JsonProperty("address_components")
    val addressComponents: kotlin.collections.List<AddressComponent>,

    /* The human-readable address of this location. */
    @field:JsonProperty("formatted_address")
    val formattedAddress: kotlin.String,

    @field:JsonProperty("geometry")
    val geometry: GeocodingGeometry,

    /* A unique identifier that can be used with other Google APIs. For example, you can use the `place_id` in a Places API request to get details of a local business, such as phone number, opening hours, user reviews, and more. See the [place ID overview](https://developers.google.com/places/place-id). */
    @field:JsonProperty("place_id")
    val placeId: kotlin.String,

    /* The `types[]` array indicates the type of the returned result. This array contains a set of zero or more tags identifying the type of feature returned in the result. For example, a geocode of \"Chicago\" returns \"locality\" which indicates that \"Chicago\" is a city, and also returns \"political\" which indicates it is a political entity. */
    @field:JsonProperty("types")
    val types: kotlin.collections.List<kotlin.String>,

    @field:JsonProperty("plus_code")
    val plusCode: PlusCode? = null,

    /* An array denoting all the localities contained in a postal code. This is only present when the result is a postal code that contains multiple localities. */
    @field:JsonProperty("postcode_localities")
    val postcodeLocalities: kotlin.collections.List<kotlin.String>? = null,

    /* Indicates that the geocoder did not return an exact match for the original request, though it was able to match part of the requested address. You may wish to examine the original request for misspellings and/or an incomplete address.  Partial matches most often occur for street addresses that do not exist within the locality you pass in the request. Partial matches may also be returned when a request matches two or more locations in the same locality.  */
    @field:JsonProperty("partial_match")
    val partialMatch: kotlin.Boolean? = null

)

