/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * An object describing a specific location with Latitude and Longitude in decimal degrees.
 *
 * @param lat Latitude in decimal degrees
 * @param lng Longitude in decimal degrees
 */

data class LatLngLiteral (

    /* Latitude in decimal degrees */
    @field:JsonProperty("lat")
    val lat: java.math.BigDecimal,

    /* Longitude in decimal degrees */
    @field:JsonProperty("lng")
    val lng: java.math.BigDecimal

)

