/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model

import org.openapi.google.model.NearestRoadsError

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param error 
 */

data class NearestRoadsErrorResponse (

    @field:JsonProperty("error")
    val error: NearestRoadsError? = null

)

