/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param code This is the same as the HTTP status of the response.
 * @param message A short description of the error.
 * @param status An error such as `INVALID_ARGUMENT`.
 */

data class NearestRoadsError (

    /* This is the same as the HTTP status of the response. */
    @field:JsonProperty("code")
    val code: java.math.BigDecimal,

    /* A short description of the error. */
    @field:JsonProperty("message")
    val message: kotlin.String,

    /* An error such as `INVALID_ARGUMENT`. */
    @field:JsonProperty("status")
    val status: kotlin.String

)

