/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model

import org.openapi.google.model.SnappedPoint

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param snappedPoints An array of snapped points.
 */

data class NearestRoadsResponse (

    /* An array of snapped points. */
    @field:JsonProperty("snappedPoints")
    val snappedPoints: kotlin.collections.List<SnappedPoint>? = null

)

