/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model

import org.openapi.google.model.Place
import org.openapi.google.model.PlacesDetailsStatus

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param htmlAttributions May contain a set of attributions about this listing which must be displayed to the user (some listings may not have attribution).
 * @param result 
 * @param status 
 * @param infoMessages When the service returns additional information about the request specification, there may be an additional `info_messages` field within the response object. This field is only returned for successful requests. It may not always be returned, and its content is subject to change. 
 */

data class PlacesDetailsResponse (

    /* May contain a set of attributions about this listing which must be displayed to the user (some listings may not have attribution). */
    @field:JsonProperty("html_attributions")
    val htmlAttributions: kotlin.collections.List<kotlin.String>,

    @field:JsonProperty("result")
    val result: Place,

    @field:JsonProperty("status")
    val status: PlacesDetailsStatus,

    /* When the service returns additional information about the request specification, there may be an additional `info_messages` field within the response object. This field is only returned for successful requests. It may not always be returned, and its content is subject to change.  */
    @field:JsonProperty("info_messages")
    val infoMessages: kotlin.collections.List<kotlin.String>? = null

)

