/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model

import org.openapi.google.model.PlaceOpeningHoursPeriodDetail

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param `open` 
 * @param close 
 */

data class PlaceOpeningHoursPeriod (

    @field:JsonProperty("open")
    val `open`: PlaceOpeningHoursPeriodDetail,

    @field:JsonProperty("close")
    val close: PlaceOpeningHoursPeriodDetail? = null

)

