/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model

import org.openapi.google.model.PlaceAutocompletePrediction
import org.openapi.google.model.PlacesAutocompleteStatus

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param predictions Contains an array of predictions. 
 * @param status 
 * @param errorMessage When the service returns a status code other than `OK<`, there may be an additional `error_message` field within the response object. This field contains more detailed information about thereasons behind the given status code. This field is not always returned, and its content is subject to change. 
 * @param infoMessages When the service returns additional information about the request specification, there may be an additional `info_messages` field within the response object. This field is only returned for successful requests. It may not always be returned, and its content is subject to change. 
 */

data class PlacesAutocompleteResponse (

    /* Contains an array of predictions.  */
    @field:JsonProperty("predictions")
    val predictions: kotlin.collections.List<PlaceAutocompletePrediction>,

    @field:JsonProperty("status")
    val status: PlacesAutocompleteStatus,

    /* When the service returns a status code other than `OK<`, there may be an additional `error_message` field within the response object. This field contains more detailed information about thereasons behind the given status code. This field is not always returned, and its content is subject to change.  */
    @field:JsonProperty("error_message")
    val errorMessage: kotlin.String? = null,

    /* When the service returns additional information about the request specification, there may be an additional `info_messages` field within the response object. This field is only returned for successful requests. It may not always be returned, and its content is subject to change.  */
    @field:JsonProperty("info_messages")
    val infoMessages: kotlin.collections.List<kotlin.String>? = null

)

