/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * A photo of a Place. The photo can be accesed via the [Place Photo](https://developers.google.com/places/web-service/photos) API using an url in the following pattern:  ``` https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&photo_reference=photo_reference&key=YOUR_API_KEY ```  See [Place Photos](https://developers.google.com/places/web-service/photos) for more information. 
 *
 * @param height The height of the photo.
 * @param width The width of the photo.
 * @param htmlAttributions The HTML attributions for the photo.
 * @param photoReference A string used to identify the photo when you perform a Photo request.
 */

data class PlacePhoto (

    /* The height of the photo. */
    @field:JsonProperty("height")
    val height: java.math.BigDecimal,

    /* The width of the photo. */
    @field:JsonProperty("width")
    val width: java.math.BigDecimal,

    /* The HTML attributions for the photo. */
    @field:JsonProperty("html_attributions")
    val htmlAttributions: kotlin.collections.List<kotlin.String>,

    /* A string used to identify the photo when you perform a Photo request. */
    @field:JsonProperty("photo_reference")
    val photoReference: kotlin.String

)

