/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param day A number from 0–6, corresponding to the days of the week, starting on Sunday. For example, 2 means Tuesday.
 * @param time May contain a time of day in 24-hour hhmm format. Values are in the range 0000–2359. The time will be reported in the place’s time zone.
 * @param date A date expressed in RFC3339 format in the local timezone for the place, for example 2010-12-31.
 * @param truncated True if a given period was truncated due to a seven-day cutoff, where the period starts before midnight on the date of the request and/or ends at or after  midnight on the last day. This property indicates that the period for open or close can extend past this seven-day cutoff.
 */

data class PlaceOpeningHoursPeriodDetail (

    /* A number from 0–6, corresponding to the days of the week, starting on Sunday. For example, 2 means Tuesday. */
    @field:JsonProperty("day")
    val day: java.math.BigDecimal,

    /* May contain a time of day in 24-hour hhmm format. Values are in the range 0000–2359. The time will be reported in the place’s time zone. */
    @field:JsonProperty("time")
    val time: kotlin.String,

    /* A date expressed in RFC3339 format in the local timezone for the place, for example 2010-12-31. */
    @field:JsonProperty("date")
    val date: kotlin.String? = null,

    /* True if a given period was truncated due to a seven-day cutoff, where the period starts before midnight on the date of the request and/or ends at or after  midnight on the last day. This property indicates that the period for open or close can extend past this seven-day cutoff. */
    @field:JsonProperty("truncated")
    val truncated: kotlin.Boolean? = null

)

