/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model

import org.openapi.google.model.PlaceAutocompleteMatchedSubstring
import org.openapi.google.model.PlaceAutocompleteStructuredFormat
import org.openapi.google.model.PlaceAutocompleteTerm

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param description Contains the human-readable name for the returned result. For `establishment` results, this is usually the business name. This content is meant to be read as-is. Do not programmatically parse the formatted address.
 * @param matchedSubstrings A list of substrings that describe the location of the entered term in the prediction result text, so that the term can be highlighted if desired.
 * @param structuredFormatting 
 * @param terms Contains an array of terms identifying each section of the returned description (a section of the description is generally terminated with a comma). Each entry in the array has a `value` field, containing the text of the term, and an `offset` field, defining the start position of this term in the description, measured in Unicode characters.
 * @param placeId A textual identifier that uniquely identifies a place. To retrieve information about the place, pass this identifier in the placeId field of a Places API request. For more information about place IDs, see the [Place IDs](https://developers.google.com/maps/documentation/places/web-service/place-id) overview.
 * @param reference See place_id.
 * @param types Contains an array of types that apply to this place. For example: `[ \"political\", \"locality\" ]` or `[ \"establishment\", \"geocode\", \"beauty_salon\" ]`. The array can contain multiple values. Learn more about [Place types](https://developers.google.com/maps/documentation/places/web-service/supported_types). 
 * @param distanceMeters The straight-line distance in meters from the origin. This field is only returned for requests made with an `origin`.
 */

data class PlaceAutocompletePrediction (

    /* Contains the human-readable name for the returned result. For `establishment` results, this is usually the business name. This content is meant to be read as-is. Do not programmatically parse the formatted address. */
    @field:JsonProperty("description")
    val description: kotlin.String,

    /* A list of substrings that describe the location of the entered term in the prediction result text, so that the term can be highlighted if desired. */
    @field:JsonProperty("matched_substrings")
    val matchedSubstrings: kotlin.collections.List<PlaceAutocompleteMatchedSubstring>,

    @field:JsonProperty("structured_formatting")
    val structuredFormatting: PlaceAutocompleteStructuredFormat,

    /* Contains an array of terms identifying each section of the returned description (a section of the description is generally terminated with a comma). Each entry in the array has a `value` field, containing the text of the term, and an `offset` field, defining the start position of this term in the description, measured in Unicode characters. */
    @field:JsonProperty("terms")
    val terms: kotlin.collections.List<PlaceAutocompleteTerm>,

    /* A textual identifier that uniquely identifies a place. To retrieve information about the place, pass this identifier in the placeId field of a Places API request. For more information about place IDs, see the [Place IDs](https://developers.google.com/maps/documentation/places/web-service/place-id) overview. */
    @field:JsonProperty("place_id")
    val placeId: kotlin.String? = null,

    /* See place_id. */
    @field:JsonProperty("reference")
    @Deprecated(message = "This property is deprecated.")
    val reference: kotlin.String? = null,

    /* Contains an array of types that apply to this place. For example: `[ \"political\", \"locality\" ]` or `[ \"establishment\", \"geocode\", \"beauty_salon\" ]`. The array can contain multiple values. Learn more about [Place types](https://developers.google.com/maps/documentation/places/web-service/supported_types).  */
    @field:JsonProperty("types")
    val types: kotlin.collections.List<kotlin.String>? = null,

    /* The straight-line distance in meters from the origin. This field is only returned for requests made with an `origin`. */
    @field:JsonProperty("distance_meters")
    val distanceMeters: kotlin.Int? = null

)

