/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model

import org.openapi.google.model.PlaceAutocompleteMatchedSubstring

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param mainText Contains the main text of a prediction, usually the name of the place.
 * @param mainTextMatchedSubstrings Contains an array with `offset` value and `length`. These describe the location of the entered term in the prediction result text, so that the term can be highlighted if desired.
 * @param secondaryText Contains the secondary text of a prediction, usually the location of the place.
 * @param secondaryTextMatchedSubstrings Contains an array with `offset` value and `length`. These describe the location of the entered term in the prediction result text, so that the term can be highlighted if desired.
 */

data class PlaceAutocompleteStructuredFormat (

    /* Contains the main text of a prediction, usually the name of the place. */
    @field:JsonProperty("main_text")
    val mainText: kotlin.String,

    /* Contains an array with `offset` value and `length`. These describe the location of the entered term in the prediction result text, so that the term can be highlighted if desired. */
    @field:JsonProperty("main_text_matched_substrings")
    val mainTextMatchedSubstrings: kotlin.collections.List<PlaceAutocompleteMatchedSubstring>,

    /* Contains the secondary text of a prediction, usually the location of the place. */
    @field:JsonProperty("secondary_text")
    val secondaryText: kotlin.String,

    /* Contains an array with `offset` value and `length`. These describe the location of the entered term in the prediction result text, so that the term can be highlighted if desired. */
    @field:JsonProperty("secondary_text_matched_substrings")
    val secondaryTextMatchedSubstrings: kotlin.collections.List<PlaceAutocompleteMatchedSubstring>? = null

)

