/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * An object containing Unix time, a time zone, and its formatted text representation.
 *
 * @param text The time specified as a string in the time zone.
 * @param `value` The time specified as Unix time, or seconds since midnight, January 1, 1970 UTC.
 * @param timeZone Contains the time zone. The value is the name of the time zone as defined in the [IANA Time Zone Database](http://www.iana.org/time-zones), e.g. \"America/New_York\".
 */

data class TimeZoneTextValueObject (

    /* The time specified as a string in the time zone. */
    @field:JsonProperty("text")
    val text: kotlin.String,

    /* The time specified as Unix time, or seconds since midnight, January 1, 1970 UTC. */
    @field:JsonProperty("value")
    val `value`: java.math.BigDecimal,

    /* Contains the time zone. The value is the name of the time zone as defined in the [IANA Time Zone Database](http://www.iana.org/time-zones), e.g. \"America/New_York\". */
    @field:JsonProperty("time_zone")
    val timeZone: kotlin.String

)

