/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model

import org.openapi.google.model.TimeZoneStatus

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param status 
 * @param dstOffset The offset for daylight-savings time in seconds. This will be zero if the time zone is not in Daylight Savings Time during the specified `timestamp`.
 * @param rawOffset The offset from UTC (in seconds) for the given location. This does not take into effect daylight savings.
 * @param timeZoneId a string containing the ID of the time zone, such as \"America/Los_Angeles\" or \"Australia/Sydney\". These IDs are defined by [Unicode Common Locale Data Repository (CLDR) project](http://cldr.unicode.org/), and currently available in file timezone.xml. When a timezone has several IDs, the canonical one is returned. In xml responses, this is the first alias of each timezone. For example, \"Asia/Calcutta\" is returned, not \"Asia/Kolkata\".
 * @param timeZoneName The long form name of the time zone. This field will be localized if the language parameter is set. eg. `Pacific Daylight Time` or `Australian Eastern Daylight Time`.
 * @param errorMessage Detailed information about the reasons behind the given status code. Included if status other than `Ok`.
 */

data class TimeZoneResponse (

    @field:JsonProperty("status")
    val status: TimeZoneStatus,

    /* The offset for daylight-savings time in seconds. This will be zero if the time zone is not in Daylight Savings Time during the specified `timestamp`. */
    @field:JsonProperty("dstOffset")
    val dstOffset: java.math.BigDecimal? = null,

    /* The offset from UTC (in seconds) for the given location. This does not take into effect daylight savings. */
    @field:JsonProperty("rawOffset")
    val rawOffset: java.math.BigDecimal? = null,

    /* a string containing the ID of the time zone, such as \"America/Los_Angeles\" or \"Australia/Sydney\". These IDs are defined by [Unicode Common Locale Data Repository (CLDR) project](http://cldr.unicode.org/), and currently available in file timezone.xml. When a timezone has several IDs, the canonical one is returned. In xml responses, this is the first alias of each timezone. For example, \"Asia/Calcutta\" is returned, not \"Asia/Kolkata\". */
    @field:JsonProperty("timeZoneId")
    val timeZoneId: kotlin.String? = null,

    /* The long form name of the time zone. This field will be localized if the language parameter is set. eg. `Pacific Daylight Time` or `Australian Eastern Daylight Time`. */
    @field:JsonProperty("timeZoneName")
    val timeZoneName: kotlin.String? = null,

    /* Detailed information about the reasons behind the given status code. Included if status other than `Ok`. */
    @field:JsonProperty("errorMessage")
    val errorMessage: kotlin.String? = null

)

