/**
 * Google Maps Platform
 *
 * API Specification for Google Maps Platform
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.google.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Attributes used to describe a WiFi access point.
 *
 * @param macAddress The MAC address of the WiFi node. It's typically called a BSS, BSSID or MAC address. Separators must be `:` (colon).
 * @param signalStrength The current signal strength measured in dBm.
 * @param signalToNoiseRatio The current signal to noise ratio measured in dB.
 * @param age The number of milliseconds since this access point was detected.
 * @param channel The channel over which the client is communication with the access point.
 */

data class WiFiAccessPoint (

    /* The MAC address of the WiFi node. It's typically called a BSS, BSSID or MAC address. Separators must be `:` (colon). */
    @field:JsonProperty("macAddress")
    val macAddress: kotlin.String,

    /* The current signal strength measured in dBm. */
    @field:JsonProperty("signalStrength")
    val signalStrength: kotlin.Int? = null,

    /* The current signal to noise ratio measured in dB. */
    @field:JsonProperty("signalToNoiseRatio")
    val signalToNoiseRatio: kotlin.Int? = null,

    /* The number of milliseconds since this access point was detected. */
    @field:JsonProperty("age")
    val age: kotlin.Int? = null,

    /* The channel over which the client is communication with the access point. */
    @field:JsonProperty("channel")
    val channel: kotlin.Int? = null

)

